<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="31" total="32" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3833" started-at="2019-10-01T21:57:13Z" finished-at="2019-10-01T21:57:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3833" started-at="2019-10-01T21:57:13Z" finished-at="2019-10-01T21:57:17Z">
      <class name="ODIN_VALIDATOR_APITEST.App1">
        <test-method status="PASS" signature="startTest()[pri:0, instance:ODIN_VALIDATOR_APITEST.App1@a67c67e]" name="startTest" is-config="true" duration-ms="742" started-at="2019-10-01T21:57:13Z" finished-at="2019-10-01T21:57:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="FAIL" signature="test32()[pri:32, instance:ODIN_VALIDATOR_APITEST.App1@a67c67e]" name="test32" duration-ms="3048" started-at="2019-10-01T21:57:14Z" finished-at="2019-10-01T21:57:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at ODIN_VALIDATOR_APITEST.App1.test32(App1.java:397)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test32 -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:ODIN_VALIDATOR_APITEST.App1@a67c67e]" name="endTest" is-config="true" duration-ms="1" started-at="2019-10-01T21:57:17Z" finished-at="2019-10-01T21:57:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- ODIN_VALIDATOR_APITEST.App1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
